environment:
  AWS_ACCESS_KEY_ID: MOCK_ID
  AWS_SECRET_ACCESS_KEY: MOCK_SECRET_KEY
  AWS_SESSION_TOKEN: MOCK_SESSION_TOKEN
  CLI_VERSION: 1.0.0-rc4-004771
  DOTNET_INSTALL_DIR: .\dotnetcli

install:
  - cinst 7zip

build_script:
  # Download and install .NET Core SDK
  - ps: (new-object System.Net.WebClient).DownloadFile("https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.ps1", "$PWD\dotnet.ps1")
  - ps: dir
  - ps: .\dotnet.ps1 -Version $env:CLI_VERSION -InstallDir $env:DOTNET_INSTALL_DIR
  # Download and run local DynamoDB
  - ps: Start-Process -NoNewWindow powershell .\scripts\local_db.ps1
  # Restore, build, test
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet build .\src\AspNetCore.Identity.DynamoDB -c Release
  - ps: dotnet build .\samples\IdentitySample.Mvc -c Release
  - ps: dotnet build .\tests\AspNetCore.Identity.DynamoDB.Tests -c Release
  - ps: dotnet test .\tests\AspNetCore.Identity.DynamoDB.Tests\AspNetCore.Identity.DynamoDB.Tests.csproj -c Release --no-build

test: off
version: '0.0.0.{build}'